### ISSUE TITLE
When there is an AREF reference to an empty Cell in gds, gdstk will break this AREF into SREF

### ISSUE THREAD

**Issue by nescirem** [heitzmann/gdstk#79]
When I used gdstk to read in the gds file containing the structure of the empty cell and the AREF referenced to the empty cell, and then wrote it out as gds, I found that the file structure had changed and the file size had become larger.

**code**:
```cpp
Library lib = read_gds("source.gds", 0, 1e-2, NULL, &error_code);
lib.write_gds("target.gds", 0, NULL);
```

**source.gds structure**:
```
AREF
SNAME "empty_CELL"
STRANS ( No_Refl )
ANGLE 90
COLROW 1 55
XY (
    202916 4283316
    202916 4283316
    179816 4283316
)
ENDEL
...
BGNSTR 2022/02/15 15:58:04 2022/02/15 15:58:04
STRNAME "empty_CELL"
ENDSTR
```

**target.gds structure**:
```
SREF
SNAME "empty_CELL"
STANS ( No_Refl )
ANGLE 90
MAG 1
XY (
    180236 4267076
)
ENDEL
SREF
SNAME "empty_CELL"
STANS ( No_Refl )
ANGLE 90
MAG 1
XY (
    180656 4267076
)
ENDEL
...  // 52 SREFs are omitted here
SREF
SNAME "empty_CELL"
STANS ( No_Refl )
ANGLE 90
MAG 1
XY (
    202916 4267076
)
ENDEL
...
BGNSTR 2022/02/25 15:58:04 2022/02/15 15:58:04
STRNAME "empty_CELL"
ENDSTR
```

**Comment by nescirem** [comment]
gdstk seems to break up some 1xN AREF into SREF, I would like to know why and how to control this.

**Comment by nescirem** [comment]
> gdstk seems to break up some 1xN AREF into SREF, I would like to know why and how to control this.

Is this preparation for the OASIS random distribution type Type 4-7?
![image](https://user-images.githubusercontent.com/26599175/155691423-26745fa8-3dcd-452d-8b57-448ca8091066.png)

**Comment by heitzmann** [comment]
@nescirem The AREF should be stored as and AREF in the target GDSII. There was a problem detecting the repetition as regular when one of the displacement vectors was zero. Should be fixed now.

**Comment by nescirem** [comment]
The problem still exists in the latest release. Is there anything I can do to help?

**Comment by heitzmann** [comment]
Can you attach de gds file in which you see the problem? From the original description, I don't see the issue any longer.

**Comment by nescirem** [comment]
I need to process the relevant files before sending them to you, maybe tomorrow.

**Comment by nescirem** [comment]
The gds files have been sent to you via email, sorry the attached image in the email seems to have been sent unsuccessfully due to network problems, repost the attached images here: 
<img src=https://user-images.githubusercontent.com/26599175/156478367-2aadb439-5965-42cc-8544-402c7bfa47e3.png width=60% /> 
fig.1 the source gds file which has 1x17 cell_16 (AREF)

<img src=https://user-images.githubusercontent.com/26599175/156478383-08dd58e0-aabe-423f-a64a-916758fb79af.png width=60% />
fig.2 the gds file processed by gdstk that break cell_16 into SREFs

**Comment by heitzmann** [comment]
@nescirem I believe the arrays are properly detected now. Let me know if it works with commit 5ffff20!

**Comment by nescirem** [comment]
I have tested dozens of examples so far without finding similar problems.
we will test hundreds of examples next, and feed back the results here.

**Comment by nescirem** [comment]
Hundreds of gds files have been tested and found everything is working fine, thank you very much for your quick response.:smile:

**Comment by nescirem** [comment]
In the latest code, there are some AREF directions that will be changed
![image](https://user-images.githubusercontent.com/26599175/163533487-8d81ea21-78b8-43ed-9607-ab5d1edb776d.png)

**Comment by heitzmann** [comment]
@nescirem Can you send me the example (or the part of the layout) that gives the wrong output?

**Comment by nescirem** [comment]
@heitzmann It may take a few days to modify and export to you. I will also be happy to help fix the problem and make a pull request.

**Comment by heitzmann** [comment]
@nescirem Thanks again for the data and report. I've added a bunch of tests in the newest commit to make sure all case I could think of pass the array detection algorithm. Please, let me know if you find any remaining bugs.
